---
title: "R Notebook"
output: html_notebook
---

# Packages

```{r}
library(blocking)
library(data.table)
library(stringi)
```

# Exercies 1

CD data

https://hpi.de/naumann/projects/repeatability/datasets/cd-datasets.html#c4374

+ data in TSV

```{r}
cd_data <- fread("https://hpi.de/fileadmin/user_upload/fachgebiete/naumann/projekte/repeatability/freeDB/mdedup/cddb.tsv", sep = "\t", colClasses = "character")
cd_data_pairs <- fread("https://hpi.de/fileadmin/user_upload/fachgebiete/naumann/projekte/repeatability/freeDB/cddb_DPL.tsv")
```

```{r}
cd_data[, txt:=paste0(artist, title, tracks, year)]
cd_data[, txt2:= stri_replace_all_regex(txt, "[^A-Za-z0-9 ]", "")]
cd_data[, row_id := as.numeric(as.factor(as.numeric(id)))]
cd_data_pairs[cd_data[, .(id1=as.integer(id), row_id)], on = "id1", x:=i.row_id]
cd_data_pairs[cd_data[, .(id2=as.integer(id), row_id)], on = "id2", y:=i.row_id]
cd_data_pairs[, block:=1:.N]
```



```{r}
controls <- controls_ann()

controls$lsh$projections <- 100
controls$lsh$hash_width <- 200
controls$lsh$tables <- 50

controls$nnd$k_build <- 60
controls$nnd$epsilon <- 0.3

test <- blocking(x = cd_data$txt2, ann = "nnd", 
                 distance = "cosine", verbose = 1, n_threads = 8,
                 control_ann = controls)
```




